--[CONSTRAINTS COMPLEMENTARES NAO GERADAS PELO AMMENTOS]
ALTER TABLE T_USUARIO ADD UNIQUE (email,inscricaoAtiva);

ALTER TABLE T_SALA     ADD COLUMN id_cconv BIGINT;

ALTER TABLE T_STAND    ADD COLUMN id_cconv BIGINT;

ALTER TABLE T_SALA     ADD CONSTRAINT fk_id_cconv_T_SALA_T_CENTROCONV      FOREIGN KEY(id_cconv)    REFERENCES T_CENTROCONV(id_cconv);

ALTER TABLE T_STAND    ADD CONSTRAINT fk_id_cconv_T_STAND_T_CENTROCONV     FOREIGN KEY(id_cconv)    REFERENCES T_CENTROCONV(id_cconv);